# nginx.conf
load_module nginx-build/objs/ngx_http_ja4_module.so;
worker_processes 1;
daemon off;
error_log stderr debug;
pid /tmp/nginx.pid;

events {
    worker_connections 64;
}

http {
    access_log off;
    default_type application/json;

    server {
        listen 8443 ssl;
        listen 8443 quic reuseport;
        server_name localhost;

        ssl_certificate certs/cert.pem;
        ssl_certificate_key certs/key.pem;
        ssl_protocols TLSv1.3;

        root .;
        index index.html index.htm;

        add_header x-ja4 $http_x_ja4 always;
        add_header x-ja4o $http_x_ja4o always;
        add_header x-ja4t $http_x_ja4t always;

        ja4_header x-ja4;
        ja4o_header x-ja4o;
        ja4t_header x-ja4t;

        location / {
            return 200 '{"ja4":"$http_x_ja4","ja4o":"$http_x_ja4o","ja4t":"$http_x_ja4t"}\n';
        }
    }
}

